# Candace Savonen Oct 2021
# Updates March 2025

name: Render R Example

# Controls when the action will run. Triggers the workflow on push
# events only for the master branch
on:
  # This makes it so you can run your github action manually if you choose
  workflow_dispatch:
  # This is set to run when any pull request is opened to main
  pull_request:
    branches: [ main ]
  # This is set to run when any Rmd, py, and sh files are pushed to main
  push:
    branches: [ main ]
    path: 
      - '*.Rmd'
      - '*.py'
      - '*.sh'

jobs:
  render-notebooks:
    # This specifies the docker image it should run on
    runs-on: ubuntu-latest
    container:
      image: jhudsl/reproducible-r

    steps:
      # We need to tell github actions to use the code on the branch we are on
      - name: checkout
        uses: actions/checkout@v4
        with:
          # How deep should it fetch?
          fetch-depth: 0

      # Run R analysis
      - name: Run R analysis example
      # Here we are telling Docker to run a single command and providing our files
      # with the --mount argument. We are telling it to run on the jhudsl/reproducible-r
      # docker image, and then the command we would like to run is `bash run_analysis.sh`
        run: bash run_analysis.sh

      - name: Commit rendered R example files
      # After it runs the analysis, we are having any changed files to be directly
      # committed to the branch we are working from
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add 01-heatmap.nb.html
          git commit -m 'Render R example' || echo "No changes to commit"
          git push origin || echo "No changes to push"
